[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
optimizer = true
optimizer_runs = 10000
via_ir = true
gas_reports = ["*"]
auto_detect_solc = false
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@oz-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "@chainlink/=lib/chainlink/",
    "forge-std/=lib/forge-std/src/"
]

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true

[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdestRemover = true
orderLiterals = true
deduplicate = true
cse = true
constantOptimizer = true
yul = true
yulDetails = { stackAllocation = true, optimizerSteps = "dhfoDgvulfnTUtnIf" }

[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"
goerli = "https://eth-goerli.g.alchemy.com/v2/demo"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/demo"
localhost = "http://localhost:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[profile.production]
via_ir = true
optimizer = true
optimizer_runs = 999999
